

export const CHANGE_TAB = 'CHANGE_TAB';
export const MINEPRESS = 'MINEPRESS';

export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'

export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS'


export const ACTION_CHANGE_APP_LOADING = 'ACTION_CHANGE_APP_LOADING'

export const ACTION_LOAD_USER_FROMLOCAL = 'ACTION_LOAD_USER_FROMLOCAL'

export const ACTION_GOT_FORGET_VCODE_SUCC = 'ACTION_GOT_FORGET_VCODE_SUCC'     //action中进行验证码成功的动作

export const ACTION_GOT_FORGET_NEXT_PAGE_SUCC = 'ACTION_GOT_FORGET_NEXT_PAGE_SUCC'     //账号验证码效验成功的动作
export const ACTION_GOT_FORGET_NEXT_PAGE_SUCC_DEL = 'ACTION_GOT_FORGET_NEXT_PAGE_SUCC_DEL'     //删除


export const ACTION_GOT_FORGET_CHANGE_CODE_SUCC = 'ACTION_GOT_FORGET_CHANGE_CODE_SUCC'     //账号验证码 更改密码
export const ACTION_GOT_FORGET_CHANGE_CODE_SUCC_DEL = 'ACTION_GOT_FORGET_CHANGE_CODE_SUCC_DEL'     //删除



export const ACTION_GET_GOOD_LIST = 'ACTION_GET_GOOD_LIST'

export const ACTION_CHANG_PASSWORD_SUCC = 'ACTION_CHANG_PASSWORD_SUCC'

export const ACTION_GET_CAR_INFO = 'ACTION_GET_CAR_INFO'

export const ACTION_GET_PERSON_INFO = 'ACTION_GET_PERSON_INFO'



export const ACTION_MAIN_PRESS = 'ACTION_MAIN_PRESS';//主界面点击事件









